# Generated by Django 5.0.6 on 2025-02-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img/')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('delivery_time', models.CharField(max_length=50)),
                ('return_policy', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('payment_method', models.CharField(choices=[('Credit Card', 'Credit Card'), ('PayPal', 'PayPal'), ('Gpay', 'Gpay')], max_length=20)),
                ('watch_type', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women')], max_length=10)),
                ('shipping_charge', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
