# Generated by Django 5.0.6 on 2025-02-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vintage_watch_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='seller_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='seller_img/')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('watch_type', models.CharField(choices=[('men', 'Men'), ('women', 'Women')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipping_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('return_policy', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=50)),
                ('delivery_time', models.CharField(max_length=100)),
                ('payment_type', models.CharField(choices=[('credit_card', 'Credit Card'), ('paypal', 'PayPal')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='payment_method',
            field=models.CharField(choices=[('Credit Card', 'Credit Card'), ('PayPal', 'PayPal'), ('Gpay', 'Gpay')], default='Credit Card', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='return_policy',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='watch_type',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women')], default='men', max_length=10),
        ),
    ]
